[package]
name = "ractors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ractors"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.95"
csv = "1.3.1"
pyo3 = "0.23.3"
